PROGRAM PCF
! Purpose:
! 	This program reads XDATCAR file generated by VASP and calculates pair
!   correlation function (PCF) for each pair of element types.

	IMPLICIT NONE
    REAL*8, PARAMETER :: pi=3.14159265358979324d0
    INTEGER n_element, start_t, end_t, skip_t
    INTEGER i, j, t, n, m, q, p, k, l
    CHARACTER*2, DIMENSION(:), ALLOCATABLE :: names
    INTEGER, DIMENSION(:), ALLOCATABLE :: n_atoms
    REAL*8, DIMENSION(3, 3) :: bravais
    REAL*8, DIMENSION(:, :, :), ALLOCATABLE :: configuration
    REAL*8, ALLOCATABLE :: r(:), gr_t(:), gr(:)
    REAL*8 len1, len2, len3, length, volume
    REAL*8 binSize, distance
   
   
! Prompt user for system specific information

    WRITE(*,*)'How many different elements do you have in your system?'
    READ(*,*) n_element
    WRITE(*,*)'How many MD steps do you wish me to throw away?'
    READ(*,*) start_t
    WRITE(*,*)'Enter the ending MD step'
    READ(*,*) end_t
    WRITE(*,*)'Enter the radial bin size for g(r) calculation:'
    READ(*,*) binSize
    WRITE(*,*)'Enter the step skip size:'
    READ(*,*) skip_t
   
   
    ALLOCATE(names(n_element))
    ALLOCATE(n_atoms(n_element))
    
	
    OPEN(501, FILE = 'XDATCAR')
    READ(501, *)
    READ(501, *)
    READ(501, *) br(1, 1), br(1, 2), br(1, 3)
    READ(501, *) br(2, 1), br(2, 2), br(2, 3)
    READ(501, *) br(3, 1), br(3, 2), br(3, 3)
    READ(501, *) names
    READ(501, *) n_atoms
    PRINT*, SUM(n_atoms)
	
	
    volume = br(1, 1) * br(2, 2) * br(3, 3) - br(1, 1) * br(2, 3) * br(3, 2) + &
             br(1, 2) * br(2, 3) * br(3, 1) - br(1, 2) * br(2, 1) * br(3, 3) + &
             br(1, 3) * br(2, 1) * br(3, 2) - br(1, 3) * br(2, 2) * br(3,1)

    len1 = SQRT(br(1, 1) * br(1, 1) + br(1, 2) * br(1, 2) + br(1, 3) * br(1, 3))
    len2 = SQRT(br(2, 1) * br(2, 1) + br(2, 2) * br(2, 2) + br(2, 3) * br(2, 3))
    len3 = sqrt(br(3, 1) * br(3, 1) + br(3, 2) * br(3, 2) + br(3, 3) * br(3, 3))
    length = MIN(len1, len2, len3)
   
   
    ALLOCATE(r(CEILING(length/binSize) - 1))
    ALLOCATE(gr(CEILING(length/binSize) - 1))
    ALLOCATE(gr_t(CEILING(length/binSize)-1))
   
   
    DO i = 1, CEILING(length/binSize)-1
	    r(i) = i * binSize
    END DO


    ALLOCATE(conf(end_t-start_t, SUM(n_atoms), 3))
    DO t = 1, end_t
        READ(501, *)
		IF (t > start_t) THEN
            DO p = 1, SUM(n_atoms)
				READ(501, *) conf(t - start_t, p, 1), conf(t - start_t, p, 2), conf(t - start_t, p, 3)
			END DO
		ELSE
			DO p = 1, SUM(n_atoms)
                READ(501, *)
			END DO
		END IF
	END DO
	
	
	DO i = 1, n_element
	DO j = i, n_element
		gr = 0
		DO t = 1, end_t - start_t, skip_t
			gr_t = 0
			DO n = SUM(n_atoms(1 : i - 1)) + 1, SUM(n_atoms(1 : i - 1)) + n_atoms(i)
			DO m = SUM(n_atoms(1 : j - 1)) + 1, SUM(n_atoms(1 : j - 1)) + n_atoms(j)
				DO q = -1,1
				DO p = -1,1
				DO k = -1,1
					distance = SQRT((br(1,1) * (conf(t, n, 1)) + br(1, 2) & 
							    *(conf(t, n, 2)) + br(1, 3) * (conf(t, n, 3)) &
							    -br(1, 1) * (conf(t, m, 1)) - br(1, 2)* &
								(conf(t, m, 2)) - br(1, 3) * (conf(t, m, 3)) + &
								br(1, 1) * q + br(2, 1) * p + br(3, 1) * k) ** 2 &
								
								+ (br(2, 1) * (conf(t, n, 1)) + br(2, 2) * &
								(conf(t, n, 2)) + br(2, 3) * (conf(t, n, 3)) &
								-br(2, 1) * (conf(t, m, 1)) - br(2, 2) * &
								(conf(t, m, 2)) - br(2, 3) * (conf(t, m, 3)) + &
								br(1, 2) * q + br(2, 2) * p + br(3, 2) * k) ** 2 &
								
								+ (br(3, 1) * (conf(t, n, 1)) + br(3, 2) * & 
								(conf(t, n, 2)) + br(3, 3) * (conf(t, n, 3)) &
								-br(3, 1) * (conf(t, m, 1)) - br(3, 2)* &
								(conf(t, m, 2)) - br(3, 3) * (conf(t, m, 3)) + &
								br(1, 3) * q + br(2, 3) * p + br(3, 3) * k) ** 2)
					IF (distance <= length) THEN
						DO l = 1, CEILING(length/binSize)-1
							IF (distance >= r(l) .AND. distance < r(l + 1)) THEN
								gr_t(l) = gr_t(l) + 1
								EXIT
							END IF
						END DO
					END IF
				
				END DO
				END DO
				END DO
			END DO
			END DO
			
 		    gr_t = gr_t / n_atoms(i)
 		    gr_t = gr_t / (n_atoms(j) / volume)
 		    gr_t = gr_t / (4 * pi * (r ** 2) * binSize)
 		    gr = gr + gr_t / (end_t - start_t) * skip_t
			
		END DO
		
! Open separate fail for each pair of elements present in XDATCAR and write radial distance
! and corresponding PCF.

        OPEN(1, FILE = TRIM(names(i))//TRIM(names(j)), STATUS = 'new')  
		DO l = 1, CEILING(length / binSize) - 1  
			WRITE(1,*) r(l), gr(l)
		END DO
	END DO
	END DO	
END PROGRAM PCF
